version: '3.8'

services:
  redis:
    image: redis:7.4.9-alpine3.21
    container_name: traceability-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - traceability-net

  solicitudes-api:
    image: ${DOCKER_USER}/api-solicitudes:latest
    container_name: traceability-solicitudes-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 9180
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_PUBLIC_KEY_LOCATION: file:/keys/public.pem
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9180/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "9180:9180"
    networks:
      - traceability-net
    volumes:
      - /home/ubuntu/docker/keys:/keys:ro

networks:
  traceability-net:
    driver: bridge

volumes:
  redis_data: