version: '3.8'

services:
  postgres-local:
    image: postgres:16-alpine
    container_name: solicitudes-postgres-local
    environment:
      POSTGRES_DB: solicitudes_db
      POSTGRES_USER: solicitudes_user
      POSTGRES_PASSWORD: solicitudes_pass
    ports:
      - "3050:5432" # Mapea el puerto 3050 de tu PC al 5432 interno del contenedor
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solicitudes_user -d solicitudes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-local:
    image: redis:7.4.9-alpine3.21
    container_name: solicitudes-redis-local
    ports:
      - "6379:6379" # Mapea el Redis local al puerto por defecto
    # Nota: No le ponemos contraseña en local para no complicarnos,
    # ya que tu application.yml por defecto la busca vacía (${REDIS_PASSWORD:})
    volumes:
      - redis_local_data:/data

volumes:
  postgres_local_data:
  redis_local_data: